# Generated by Django 3.1.14 on 2022-03-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0004_auto_20220228_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='icon',
            field=models.CharField(choices=[('fas fa-cog', 'Cog'), ('fas fa-play', 'Play'), ('fas fa-stop', 'Stop'), ('fas fa-file', 'File'), ('fas fa-folder-plus', 'Patch'), ('fab fa-wpexplorer', 'Explore'), ('fas fa-clone', 'Clone'), ('fas fa-window-restore', 'Restore'), ('fas fa-level-up-alt', 'LevelUp'), ('fas fa-hdd', 'HardDisk'), ('fas fa-sort-desc', 'Deprov')], default='fas fa-cog', max_length=40),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('EXTEND', 'Extend'), ('SCALEOUT', 'Scaleout')], default='CREATE', max_length=10, verbose_name='Operation type'),
        ),
    ]
